version: '1.0'

input:
  - hosts

tasks:
  get_configs:
    action: arista.get_config
    input:
      hosts: "{{ ctx().hosts }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - configs: "{{ result().output.result }}"
        do: generate_date

  generate_date:
    action: core.local
    input:
      cmd: "date '+%Y-%m-%d-%H-%M-%S'"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - date: "{{ result().stdout }}"
        do: write_configs

  write_configs:
    action: core.local
    with: "{{ ctx().configs }}"
    input:
      cmd: |
        echo '{{ item().confg.candidate }}' > /arista/{{ ctx().date }}_{{ item().host }}_candidate.conf;
        echo '{{ item().confg.running }}' > /arista/{{ ctx().date }}_{{ item().host }}_running.conf;
        echo '{{ item().confg.startup }}' > /arista/{{ ctx().date }}_{{ item().host }}_startup.conf;

output:
  - date: "{{ ctx().date }}"
  - hosts: "{{ ctx().hosts }}"
