version: '1.0'

input:
  - hosts

tasks:
  get_config:
    action: arista.get_config_host
    with: "{{ ctx().hosts }}"
    input:
      host: "{{ item() }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - result: "{{ result() }}"

output:
  - result: "{{ ctx().result }}"
