version: '1.0'

input:
  - hosts
  - config

tasks:
  loadconfigs:
    action: napalm.loadconfig
    with: "{{ ctx().hosts }}"
    input:
      hostname: "{{ ctx().hostname }}"
      config_text: "{{ ctx().config }}"
    next:
      - when: "{{ succeeded() }}"
        publish:
          - result: "{{ result() | map(attribute='result') | list }}"

output:
  result: "{{ ctx().result }}"
