---
- name: Gather logs data for all hosts in the fabric
  hosts: all
  gather_facts: false

  tasks:
    - name: Get logs
      eos_command:
        commands: "show log {{ num_logs | default(10) }}"
