---
- name: Enable eAPI and fix LLDP neighbor issue in the Arista lab
  hosts: all
  gather_facts: false

  tasks:
    - name: Enable eAPI
      eos_config:
        lines:
          - lldp management-address Management 1
          - management api http-commands
          -    no shutdown
          - end
