---
description: "Gets the config from a single host"
enabled: true
entry_point: workflows/get_config_host.yaml
name: get_config_host
pack: arista
runner_type: "orquesta"
parameters:
  host:
    type: string
    description: "Name of a host"
  skip_notify:
    type: array
    default:
      - get_config
